# Site
repository: caleblareau/caleblareau.github.io
favicon: images/favicon_ico

# Content configuration version
version: 2

# Personal info
name: Caleb Lareau
title: Stanford Science Fellow
email: clareau@stanford.edu
email_title: Contact
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
#website: https://profiles.stanford.edu/caleb-lareau
#website_title: Stanford Profile

# Dark Mode (true/false/never)
darkmode: false

# Social links
orcid_username: 0000-0003-4179-4807
twitter_username: caleblareau
github_username:  caleblareau
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: caleblareau
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

# Additional icon links
additional_links:
- title: Google Scholar
  icon: fas fa-graduation-cap
  url: https://scholar.google.com/citations?user=e_8eOmYAAAAJ&hl=en&inst=5746887945952177237&oi=ao
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About
about_profile_image: images/on2.png
about_content: | # this will include new lines to allow paragraphs
 I am currently a [Stanford Science Fellow](https://stanfordsciencefellows.stanford.edu/meet-fellows)
 in the School of Medicine at Stanford University and [Parker Scholar](https://www.parkerici.org/the-latest/funding-the-future-of-cancer-research-the-parker-institute-for-cancer-immunotherapy-awards-nearly-3-million-to-six-early-career-researchers/) 
 at the Parker Institute of Cancer Immunotherapy. My research concerns the development and application of genomics
 technologies to inform properties of human physiology, including the somatic changes in tissues and the dynamics of 
 immune cells within the complex tissues such as humans.


 
 
 My work at Stanford is mentored by [Ansuman Satpathy](https://satpathylab.com/lab/) and
 [Anshul Kundaje](https://sites.google.com/site/anshulkundaje/students)
 in the Departments of Pathology and Genetics at the School of Medicine. 
 [A complete CV is available here](https://cap.stanford.edu/profiles/viewCV?facultyId=241457&name=Caleb_Lareau).
 

content:
  - title: Experience
    layout: list
    content:
      - layout: top-left
        title: Stanford University
        sub_title: Fellow
        caption: July 2020 - Present
        link: 
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          I currently hold an appointment in the Department of Pathology and the Department of Genetics at Stanford University School of Medicine
      - layout: top-left
        title: Harvard University
        sub_title: Graduate Student
        caption: August 2015-June 2020
        link: 
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          I completed my graduate studies at Harvard Medical School, where I earned my PhD in the Division of Medicine Sciences. 
      - layout: top-left
        title: University of Tulsa
        sub_title: Undergraduate Student
        caption: August 2011-May 2015
        link: 
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          I completed my undergraduate education. 

  - title: Honors and Awards
    layout: text
    content: | # this will include new lines to allow paragraphs
      - [Parker Scholar](https://www.10xgenomics.com/blog/introducing-the-innovator-series-hacking-atac-seq-to-perform-clonal-lineage-tracing-in-tumors), Parker Institute for Cancer Immuno
      - [An expanded arsenal of single-cell methods](https://www.nature.com/articles/s41592-021-01245-w)
      - [The 'kitchen-seq' of single-cell multiomics analyses](https://www.nature.com/articles/d41586-021-01994-w)
      - [How SARS-CoV-2 interacts with cells](https://www.sciencedaily.com/releases/2020/12/201221121725.htm)
      - [Accelerating single-cell research](https://news.harvard.edu/gazette/story/2019/06/new-atac-seq-method-from-harvard-accelerates-single-cell-research/)
      - [Unexpected mutations caused by CRISPR have a diferent explanation](https://www.forbes.com/sites/stevensalzberg/2017/07/10/crispr-gene-editing-problems-does-it-really-cause-unexpected-mutations/?sh=720f120c6a1a)


  - title: In the News
    layout: text
    content: | # this will include new lines to allow paragraphs
      - [Hacking single-cell technologies to trace lineages in cancer](https://www.10xgenomics.com/blog/introducing-the-innovator-series-hacking-atac-seq-to-perform-clonal-lineage-tracing-in-tumors)
        - 10x Genomics Innovator Feature, _August 2021_
      - [An expanded arsenal of single-cell methods via DOGMA-seq](https://www.nature.com/articles/s41592-021-01245-w)
        - _Nature Methods_, August 2021
      - [The 'kitchen-seq' of single-cell multiomics analyses](https://www.nature.com/articles/d41586-021-01994-w)
        - _Nature_, July 2021
      - [A comprehensive map of how the SARS-CoV-2 RNA interacts with cells](https://www.sciencedaily.com/releases/2020/12/201221121725.htm)
        - _Science Daily_, December 2020
      - [Accelerating single-cell research via droplet microfluidics](https://news.harvard.edu/gazette/story/2019/06/new-atac-seq-method-from-harvard-accelerates-single-cell-research/)
        - _Harvard Gazette_, June 2019
      - [Unexpected mutations caused by CRISPR have a different explanation](https://www.forbes.com/sites/stevensalzberg/2017/07/10/crispr-gene-editing-problems-does-it-really-cause-unexpected-mutations/?sh=720f120c6a1a)
        - _Forbes_, July 2017




# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
